Add Color to Opticharging
Signed-off-by: Chester Kener <Cl3Kener@gmail.com>

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 #
-# Super-mega opticharger of doom
+# Super-mega Hellkat opticharger of doom
 # Shrinks apks by running pngcrush or optipng or pngout on png images
 #
 # Point APKCERTS at the full path to a generated apkcerts.txt file, such as:
@@ -14,6 +14,7 @@ QUIET=1
 BASE=`pwd`
 BRUTECRUSH="-brute"
 TMPDIR=/tmp/opticharge-$$
+. $ANDROID_BUILD_TOP/vendor/slim/tools/functions
 
 if [ -z "$BRUTE_PNGCRUSH" ]
 then
@@ -31,14 +32,14 @@ then
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo "Set APKCERTS to the path to your apkcerts.txt file"
+        echo -e $CL_RED"Set APKCERTS to the path to your apkcerts.txt file"$CL_RST
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo "Invalid path to apkcerts.txt, set APKCERTS to the correct path."
+    echo -e $CL_RED"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$CL_RST
 fi
 
 if [ "$(which pngquant)" != "" ];
@@ -50,7 +51,7 @@ elif [ "$(which pngcrush)" != "" ];
 then
     optimize_png () {
         pngcrush -q ${BRUTECRUSH} $1 ${1}.out 1> /dev/null 2> /dev/null
-        mv ${1}.out ${1}
+        mv ${1}.out ${1} 2> /dev/null
     }
 elif [ "$(which optipng)" != "" ];
 then
@@ -68,26 +69,26 @@ then
         pngout $1
     }
 else
-    echo "Please install pngquant, pngcrush, optipng, or pngout"
+    echo -e $CL_RED"Please install pngquant, pngcrush, optipng, or pngout"$CL_RST
     exit 1;
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo "Please ensure aapt is in your \$PATH"
+    echo -e $CL_RED"Please ensure aapt is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo "Please ensure zipalign is in your \$PATH"
+    echo -e $CL_RED"Please ensure zipalign is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo "Optimizing $NAME...";
+    echo -e $CL_RED"Optimize:"$CL_RST" $NAME..";
 
     if [ "$2" != "" ];
     then
@@ -95,7 +96,7 @@ then
         KEY=build/target/product/security/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo "$CERT does not exist!";
+            echo -e $CL_RED"$CERT does not exist!"$CL_RST;
             exit 1;
         fi
     else
@@ -103,24 +104,24 @@ then
         [ $QUIET ] || echo "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo "No apk info for $NAME";
+            echo -e $CL_RED"No apk info for $NAME"$CL_RST;
             exit 1;
         fi
         CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
         KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo "Unable to find certificate for $NAME"
+            echo -e $CL_RED"Unable to find certificate for $NAME"$CL_RST
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo "$NAME is presigned, skipping"
+            echo -e $CL_GRN"$NAME is presigned, skipping"$CL_RST
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo "Certificate: $CERT";
+    [ $QUIET ] || echo -e $CL_GRN"Certificate:"$CL_RST" $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
@@ -129,19 +130,19 @@ then
     unzip -q $BASE/$1
     for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
     do
-        [ $QUIET ] || echo "Crushing $x"
+        [ $QUIET ] || echo -e $CL_RED"Crushing $x"$CL_RST
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo "Repacking apk.."
+    [ $QUIET ] || echo -e $CL_RED"Repacking apk.."$CL_RST
     aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
-    
-    [ $QUIET ] || echo "Resigning with cert: `echo $CERT`"
+
+    [ $QUIET ] || echo -e $CL_RED"Resigning with cert: `echo $CERT`"$CL_RST
 
     [ $QUIET ] || echo java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
     java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    [ $QUIET ] || echo "Zipalign.."
+    [ $QUIET ] || echo -e $CL_RED"Zipaligning.."$CL_RST
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -3,6 +3,7 @@
 # Squish a CM otapackage for distribution
 # cyanogen
 #
+. $ANDROID_BUILD_TOP/vendor/slim/tools/functions
 
 OUT_TARGET_HOST=`uname -a | grep Darwin`
 if [ -z "$OUT_TARGET_HOST" ]
@@ -19,8 +20,8 @@ else
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-    echo "ERROR: $0 only works with a full build environment. $OUT should exist."
-    exit 1
+	echo $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+	exit 1
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
@@ -205,7 +206,19 @@ img=`basename $OUTFILE`
 cd `dirname $OUTFILE`
 $MD5 $img >$img.md5sum
 echo
-echo "Package complete: $OUTFILE"
+echo -e ${CL_RED}"                                     "${CL_RST}
+echo -e ${CL_RED}"    )                   )            "${CL_RST}
+echo -e ${CL_RED}" ( /(   )   (   (    ( /(          ) "${CL_RST}
+echo -e ${CL_RED}" )\())  )(  )\  )\   )\())   )  ( /( "${CL_RST}
+echo -e ${CL_RED}"((_)\   /)\((_)((_) ((_)\ ( /(  )\())"${CL_RST}
+echo -e ${CL_RED}" _((_) /((_)_) )_/ )_(((_))(_))(_))/ "${CL_RST}
+echo -e ${CL_RED}"| || |(_)) | | | | | |/ /((_)_ | |_  "${CL_RST}
+echo -e ${CL_RED}"| __ |/ -_)| | | | | ' < / _' ||  _| "${CL_RST}
+echo -e ${CL_RED}"|_||_|\___||_| |_| |_|\_\\__,_| \__| "${CL_RST}
+echo -e ${CL_RED}"                                     "${CL_RST}
+echo -e ${CL_RED}"                                     "${CL_RST}
+echo -e ${CL_RED}"                                     "${CL_RST}
+echo -e ${CL_RED}"Package Complete: $OUTFILE"${CL_RST}
 cat $img.md5sum
 echo
 )
